src/Entity/Decision.php
<?php

namespace App\Entity;

use DateTime;
use DateTimeInterface;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinTable;
use App\Repository\DecisionRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: DecisionRepository::class)]
#[Vich\Uploadable]
/** @SuppressWarnings(PHPMD.ExcessiveClassComplexity) */
class Decision
{
    public const STATUS = [
        'opened' => 'Prise de décision commencée',
        'accepted' => 'Décision aboutie',
        'conflict' => 'Conflit sur la décision',
        'modified' => 'Décision définitive',
        'refused' => 'Décision non aboutie',
        'ended' => 'Décision terminée'
    ];

    public const WORKFLOWS = [
        'to_decision_opened_accepted' => 'Passer au statut accepté',
        'to_decision_opened_conflict' => 'Passer au statut conflit',
        'to_decision_opened_refused' => 'Passer au statut en conflit',
        'to_conflict_modified' => 'Passer au statut deuxième décision',
        'to_modified_accepted' => 'Passer au statut accepté',
        'to_modified_refused' => 'Passer au statut refusé',
        'to_accepted_ended' => 'Passer au statut terminé',
        'to_refused_ended' => 'Passer au statut terminé',
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\GreaterThanOrEqual('today')]
    #[Assert\NotNull]
    private ?\DateTimeInterface $startDate = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'decisions')]
    private ?Category $category = null;

    #[ORM\OneToMany(mappedBy: 'decision', targetEntity: Comment::class, cascade: ["remove"])]
    private Collection $comments;

    #[ORM\ManyToOne(inversedBy: 'decisions')]
    private ?User $user = null;

    #[ORM\Column(type: 'string')]
    private ?string $currentPlace = 'opened';

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $image = null;

    #[Vich\UploadableField(mapping: 'decision_file', fileNameProperty: 'image')]
    #[Assert\File(
        maxSize: '1M',
        mimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    )]
    private ?File $imageFile = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?DatetimeInterface $updatedAt = null;
    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'expertUsers', cascade: ["remove"])]
    #[JoinTable('expert_user')]
    private Collection $expertUsers;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'impactedUsers', cascade: ["remove"])]
    #[JoinTable('impacted_user')]
    private Collection $impactedUsers;

    #[ORM\OneToMany(mappedBy: 'decision', targetEntity: Vote::class, cascade: ["remove"])]
    private Collection $votes;
    #[ORM\OneToMany(mappedBy: 'decision', targetEntity: Notification::class, cascade: ["remove"], orphanRemoval: true)]
    private Collection $notifications;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->expertUsers = new ArrayCollection();
        $this->impactedUsers = new ArrayCollection();
        $this->votes = new ArrayCollection();
        $this->notifications = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStatus(): ?string
    {
        return  self::STATUS[$this->getCurrentPlace()];
    }


    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setDecision($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getDecision() === $this) {
                $comment->setDecision(null);
            }
        }
        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function setImageFile(File $image = null): Decision
    {
        $this->imageFile = $image;
        if ($image) {
            $this->updatedAt = new DateTime('now');
        }
        return $this;
    }
    public function getCurrentPlace(): ?string
    {
        return $this->currentPlace;
    }

    public function setCurrentPlace(?string $currentPlace, ?array $context = []): void
    {
        $this->currentPlace = $currentPlace;
    }

    /**
     * @return Collection<int, User>
     */
    public function getExpertUsers(): Collection
    {
        return $this->expertUsers;
    }

    public function addExpertUser(User $expertUser): static
    {
        if (!$this->expertUsers->contains($expertUser)) {
            $this->expertUsers->add($expertUser);
        }

        return $this;
    }

    public function removeExpertUser(User $expertUser): static
    {
        $this->expertUsers->removeElement($expertUser);

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getImpactedUsers(): Collection
    {
        return $this->impactedUsers;
    }

    public function addImpactedUser(User $impactedUser): static
    {
        if (!$this->impactedUsers->contains($impactedUser)) {
            $this->impactedUsers->add($impactedUser);
        }

        return $this;
    }

    public function removeImpactedUser(User $impactedUser): static
    {
        $this->impactedUsers->removeElement($impactedUser);

        return $this;
    }
    /**
     * @return Collection<int, Vote>
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }

    public function addVote(Vote $vote): static
    {
        if (!$this->votes->contains($vote)) {
            $this->votes->add($vote);
            $vote->setDecision($this);
        }

        return $this;
    }

    public function removeVote(Vote $vote): static
    {
        if ($this->votes->removeElement($vote)) {
            // set the owning side to null (unless already changed)
            if ($vote->getDecision() === $this) {
                $vote->setDecision(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Notification>
     */

    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): static
    {
        if (!$this->notifications->contains($notification)) {
            $this->notifications->add($notification);
            $notification->setDecision($this);
        }
        return $this;
    }

    public function removeNotification(Notification $notification): static
    {
        if ($this->notifications->removeElement($notification)) {
            // set the owning side to null (unless already changed)
            if ($notification->getDecision() === $this) {
                $notification->setDecision(null);
            }
        }
        return $this;
    }

    public function getPositiveVote(): int
    {
        $total = 0;
        foreach ($this->getVotes() as $vote) {
            if ($vote->getVoting() === 1) {
                $total++;
            }
        }
        return $total;
    }

    public function getNegativeVote(): int
    {
        $total = 0;
        foreach ($this->getVotes() as $vote) {
            if ($vote->getVoting() === -1) {
                $total++;
            }
        }
        return $total;
    }
}

src/Controller/DecisionController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Decision;
use App\Entity\Notification;
use App\Form\CommentType;
use App\Form\DecisionType;
use Symfony\Component\Mime\Email;
use App\Repository\CommentRepository;
use App\Repository\DecisionRepository;
use App\Repository\VoteRepository;
use App\Repository\NotificationRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Workflow\WorkflowInterface;
use Symfony\Component\ExpressionLanguage\Expression;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Service\WorkflowAdvancement;

#[Route('/decision')]
class DecisionController extends AbstractController
{
    #[Route('/', name: 'app_decision_index', methods: ['GET', 'POST'])]
    public function index(DecisionRepository $decisionRepository): Response
    {

        return $this->render('admin/admin_decision/index.html.twig', [
            'decisions' => $decisionRepository->findAll(),
        ]);
    }

    #[Route('/ajouter', name: 'app_decision_new', methods: ['GET', 'POST'])]
    public function new(
        Request $request,
        DecisionRepository $decisionRepository,
        NotificationRepository $notifRepository,
        MailerInterface $mailer
    ): Response {

        $decision = new Decision();
        $form = $this->createForm(DecisionType::class, $decision);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $decision->setUser($this->getUser());
            $decisionRepository->save($decision, true);

            $this->addFlash('success', 'La nouvelle décision a bien été créée.');

            $expertUsers = $decision->getExpertUsers();
            foreach ($expertUsers as $user) {
                $email = (new Email())
                    ->from($this->getParameter('mailer_from'))
                    ->to($user->getEmail())
                    ->subject('(Makesense) nouvelle décision')
                    ->html($this->renderView('decision/newEmailExpert.html.twig', ['decision' => $decision,]));
                $mailer->send($email);
                $notif = new Notification();
                $notif->setDecision($decision);
                $notif->setUser($user);
                $notif->setMessage($decision->getTitle());
                $notif->setIsRead(false);
                $notifRepository->save($notif, true);
            }
            $impactedUsers = $decision->getImpactedUsers();
            foreach ($impactedUsers as $user) {
                $email = (new Email())
                    ->from($this->getParameter('mailer_from'))
                    ->to($user->getEmail())
                    ->subject('(Makesense) nouvelle décision')
                    ->html($this->renderView('decision/newEmailImpacted.html.twig', ['decision' => $decision]));
                $mailer->send($email);
                $notif = new Notification();
                $notif->setDecision($decision);
                $notif->setUser($user);
                $notif->setMessage($decision->getTitle());
                $notif->setIsRead(false);
                $notifRepository->save($notif, true);
            }

            return $this->redirectToRoute('status_home', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('decision/new.html.twig', [
            'decision' => $decision,
            'form' => $form,
        ]);
    }

    #[Route('/archive', name: 'app_archive')]
    public function archive(DecisionRepository $decisionRepository): Response
    {
        return $this->render('decision/archive.html.twig', [
            'decisions' => $decisionRepository->findall(),
        ]);
    }

    #[Route('/change/{id}/{toStatus}', name: 'app_change', methods: ['POST'])]
    public function change(
        Decision $decision,
        string $toStatus,
        DecisionRepository $decisionRepository,
        WorkflowInterface $decisionStateMachine,
    ): Response {

        if ($toStatus && $decisionStateMachine->can($decision, $toStatus)) {
            $decisionStateMachine->apply($decision, $toStatus);
            $decisionRepository->save($decision, true);
        }

        return $this->redirectToRoute('app_decision_show', ['id' => $decision->getId()], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}', name: 'app_decision_show', methods: ['GET', 'POST'])]
    public function show(Request $request, Decision $decision, CommentRepository $commentRepository): Response
    {

        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setUser($this->getUser());
            $comment->setDecision($decision);
            $commentRepository->save($comment, true);

            $this->addFlash('success', 'Votre commentaire a bien été ajouté.');

            return $this->redirectToRoute('app_decision_show', ['id' => $decision->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('decision/show.html.twig', [
            'decision' => $decision,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_decision_edit', methods: ['GET', 'POST'])]
    #[IsGranted(
        attribute: new Expression('user === subject'),
        subject: new Expression('args["decision"].getUser()'),
    )]
    public function edit(
        Request $request,
        Decision $decision,
        DecisionRepository $decisionRepository,
        WorkflowAdvancement $workflowAdvancement
    ): Response {
        $workflowName = $workflowAdvancement->stepStatus($decision);

        $decision->setUser($this->getUser());
        $form = $this->createForm(DecisionType::class, $decision);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $decision = $form->getData();

            $decisionRepository->save($decision, true);

            $this->addFlash('success', 'La décision a bien été modifiée.');

            return $this->redirectToRoute('status_home', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('decision/edit.html.twig', [
            'decision' => $decision,
            'form' => $form,
            'workflowName' => $workflowName,
        ]);
    }

    #[Route('/{id}', name: 'app_decision_delete', methods: ['POST'])]
    public function delete(Request $request, Decision $decision, DecisionRepository $decisionRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $decision->getId(), $request->request->get('_token'))) {
            $decisionRepository->remove($decision, true);
            $this->addFlash('success', 'La décision a bien été supprimée.');
        }

        return $this->redirectToRoute('status_home', [], Response::HTTP_SEE_OTHER);
    }
}

templates/decision/_delete_form.html.twig
<form method="post" action="{{ path('app_decision_delete', {'id': decision.id}) }}" onsubmit="return confirm('Êtes-vous certain de vouloir supprimer?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ decision.id) }}">
	<div class="text-end">
		<button class="btn btn-light text-primary my-2 border border-secondary bg-white fw-bold rounded-pill mt-5">Supprimer</button>

	</div>
</form>

templates/decision/_form.html.twig
{{ form_start(form) }}

{# {{ form_widget(form) }} #}
<div class="col">
	{{ form_row(form.title, {'attr': {'class': 'form-class text text-primary fw-bold'}}) }}
</div>
<div class="col">
	{{ form_row(form.startDate, {'attr': {'class': 'form-class text text-primary fw-bold'}}) }}
</div>
<div class="selection-decision d-flex flex-column flex-md-row  gap-3">
	<div class="col">
		{{ form_row(form.category, {'attr': {'class': 'form-class text text-primary fw-bold'}}) }}
	</div>

	<div class="col">
		{{ form_row(form.expertUsers, {'attr': {'class': 'form-class text text-primary fw-bold border border-light form-control bg-tertiary', 'placeholder': 'Personne experte'}}) }}

	</div>
	<div class="col">
		{{ form_row(form.impactedUsers, {'attr': {'class': 'form-class text text-primary fw-bold border border-light form-control bg-tertiary'}}) }}
	</div>
</div>
<div>
	{{ form_row(form.imageFile, {'attr': {'class': 'form-class text text-primary fw-bold border border-2  border-secondary form-control mb-3'}}) }}

</div>


<div class="col">
	{{ form_row(form.description, {'attr': {'class': 'form-class text text-primary fw-bold border border-light form-control bg-tertiary'}}) }}
</div>


<button class="btn btn-light rounded-pill px-3 my-4 text-primary fw-bold">{{ button_label|default('Soumettre') }}</button>

{{ form_end(form) }}

templates/decision/archive.html.twig
{% extends 'base.html.twig' %}


{% block title %}Décision archivées
{% endblock %}

{% block body %}

	<div class="title d-flex justify-content-center">
		<h1 class="text-center fw-bold fs-1 my-5">Les
			<span class="pastille"></span>
			archives
		</h1>

	</div>
	<div class="decision" id="cardsContainer">
		<div class="container g-0">
			<div class="row">

				{% for decision in decisions %}
					{% if decision.status == constant('App\\Entity\\Decision::STATUS')['ended'] %}
						<div class="col-lg-4 col-md-6">
							<div class="card shadow mb-5 border border-0 rounded bg-tertiary">
								<div class="card-body">
									<div class="img-container">
										{% if decision.image %}
											<img class="img" src="{{ asset('uploads/images/decision/' ~ decision.image)}}">
										{% else %}
											<img class="img" src="{{ asset('uploads/images/category/' ~ decision.category.image) }}" alt="Image">
										{% endif %}
									</div>
									<div class="position-relative">

										<div class="card-main">
											{% if decision.user.avatar %}
												<a href="{{ path('app_profile', {'id': decision.user.id}) }}">
													<img class="img-profile rounded-circle position-absolute mx-4" src="{{ asset('uploads/avatar/' ~ decision.user.avatar) }}">
												</a>
											{% else %}
												<a href="{{ path('app_profile', {'id': decision.user.id}) }}">
													<img class="img-profile rounded-circle position-absolute mx-4" src="{{ asset('build/images/profil.png')}}">
												</a>
											{% endif %}
											<div class="color-card">
												<a href="{{ path('app_profile', {'id': decision.user.id}) }}">
													<p class="text-tertiary border-primary fw-bolder fs-5 mx-3 mb-2 border-5 px-2 pb-1 pt-5 border-bottom">{{ decision.user.fullname }}</p>
												</a>
											</div>
										</div>
									</div>
									<div class="statut pt-2 mx-3 text-end">

										{% if decision.votes|filter(vote => vote.voting == 1)|length > decision.votes|filter(vote => vote.voting == -1)|length %}
											<p class="label-status badge rounded-pill p-2">Décision acceptée</p>
										{% else %}
											<p class="label-status badge rounded-pill p-2">Décision refusée</p>

										{% endif %}
										<div class="label-category badge rounded-pill p-2">

											{{ decision.category.title }}
										</div>
									</div>
									<h2 class="card-title text-primary fw-bolder p-3 fs-4 mb-0">
										{{ decision.title|u.truncate(50, '...') }}
									</h2>

									<div class="text-end p-3 text-l pt-0 primary mb-1 btn-rounded">
										{% if app.user == decision.user %}
											<a href="{{ path('app_decision_edit', {'id': decision.id}) }}" class="btn btn-card btn-primary mt-3 px-3 rounded-pill text-light bg-primary fw-bold">Modifier</a>
										{% endif %}
										<a href="{{ path('app_decision_show', {'id': decision.id}) }}" class="btn btn-card btn-light mt-3 px-3 rounded-pill text-primary bg-light fw-bold ms-4">En savoir plus</a>

									</div>
									<div class="vote bg-light rounded-pill p-1 px-2">
										<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#507178" class="bi bi-hand-thumbs-up-fill" viewbox="0 0 16 16">
											<path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
										</svg>
										{{ decision.votes|filter(vote => vote.voting == 1)|length }}
										<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#507178" class="bi bi-hand-thumbs-down-fill ms-2" viewbox="0 0 16 16">

											<path d="M6.956 14.534c.065.936.952 1.659 1.908 1.42l.261-.065a1.378 1.378 0 0 0 1.012-.965c.22-.816.533-2.512.062-4.51.136.02.285.037.443.051.713.065 1.669.071 2.516-.211.518-.173.994-.68 1.2-1.272a1.896 1.896 0 0 0-.234-1.734c.058-.118.103-.242.138-.362.077-.27.113-.568.113-.856 0-.29-.036-.586-.113-.857a2.094 2.094 0 0 0-.16-.403c.169-.387.107-.82-.003-1.149a3.162 3.162 0 0 0-.488-.9c.054-.153.076-.313.076-.465a1.86 1.86 0 0 0-.253-.912C13.1.757 12.437.28 11.5.28H8c-.605 0-1.07.08-1.466.217a4.823 4.823 0 0 0-.97.485l-.048.029c-.504.308-.999.61-2.068.723C2.682 1.815 2 2.434 2 3.279v4c0 .851.685 1.433 1.357 1.616.849.232 1.574.787 2.132 1.41.56.626.914 1.28 1.039 1.638.199.575.356 1.54.428 2.591z"/>
										</svg>
										{{ decision.votes|filter(vote => vote.voting == -1)|length }}
									</div>
								</div>
							</div>
						</div>
					{% endif %}
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

templates/decision/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier décision
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('addDecision') }}
{% endblock %}

{% block body %}
	<h1 class="text-primary text-center fw-bold fs-1 mt-5">Gérer ma décision</h1>
	<div class="container bg-light rounded  p-4">
		{% include 'components/_workflowStatus.html.twig' %}
		<h4 class="fw-bold text-primary mt-2 mb-4">
			{{ decision.status }}
		</h4>
		{{ include('decision/_form.html.twig', {'button_label': 'Mise à jour'}) }}
		{{ include('decision/_delete_form.html.twig') }}
		<div class="form-decision">
			<a href="{{ path('status_my_decision') }}" class="btn btn-primary fw-bold rounded-pill px-3 mb-5">Retour</a>
		</div>


	</div>
{% endblock %}

templates/decision/new.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('addDecision') }}
{% endblock %}

{% block title %}
	Ajouter une décision
{% endblock %}

{% block body %}
	<h1 class="text-center fw-bold mt-5">Ajouter une nouvelle décision</h1>
	<div class="container p-5 rounded">
		{{ include('decision/_form.html.twig') }}
		<div class="container px-0">
			<a class="btn btn-light mt-3 px-3 rounded-pill text-tertiary bg-primary fw-bold" href="{{ path('status_home') }}">Retour</a>
		</div>
	</div>
{% endblock %}

templates/decision/newEmailExpert.html.twig
{% extends 'baseEmail.html.twig' %}

{% block body %}
<h1>Vous êtes expert de cette nouvelle décision.</h1>
{{ parent() }}
{% endblock %}

templates/decision/newEmailImpacted.html.twig
{% extends 'baseEmail.html.twig' %}

{% block body %}
<h1>Vous êtes impacté par cette nouvelle décision.</h1>
{{ parent() }}
{% endblock %}