src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Ignore;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[Vich\Uploadable]
#[UniqueEntity(fields: ['email'], message: 'Cette adresse email existe déjà.')]
/**
 *  @SuppressWarnings(PHPMD.ExcessiveClassComplexity)
 *  @SuppressWarnings(PHPMD.ExcessivePublicCount)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    public function __serialize(): array
    {
        return [
            'id' => $this->id,
            'email' => $this->email,
            'password' => $this->password,
        ];
    }
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 180)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Comment::class)]
    private Collection $comments;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 255)]
    private ?string $firstname = null;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 255)]
    private ?string $lastname = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Decision::class)]
    private Collection $decisions;

    #[ORM\Column(type: Types::TEXT, nullable: true, length: 250)]
    #[Assert\Length(max: 250)]
    private ?string $biography = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $avatar = null;

    #[Vich\UploadableField(mapping: 'user_avatar', fileNameProperty: 'avatar')]
    #[Assert\File(
        maxSize: '1M',
        mimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    )]
    #[Ignore]
    private ?File $avatarFile = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?DateTimeInterface $updatedAt = null;

    #[ORM\ManyToMany(targetEntity: Decision::class, mappedBy: 'expertUsers')]
    private Collection $expertUsers;

    #[ORM\ManyToMany(targetEntity: Decision::class, mappedBy: 'impactedUsers')]
    private Collection $impactedUsers;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Notification::class, orphanRemoval: true)]
    private Collection $notifications;

    #[ORM\Column(nullable: true)]
    private ?bool $isActivated = false;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Vote::class)]
    private Collection $votes;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->decisions = new ArrayCollection();
        $this->expertUsers = new ArrayCollection();
        $this->impactedUsers = new ArrayCollection();
        $this->notifications = new ArrayCollection();
        $this->votes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {

        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
    public function getFirstname(): ?string
    {
        return $this->firstname;
    }
    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;
        return $this;
    }
    public function getLastname(): ?string
    {
        return $this->lastname;
    }
    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;
        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    public function getFullname(): ?string
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    /**
     * @return Collection<int, Decision>
     */
    public function getDecisions(): Collection
    {
        return $this->decisions;
    }

    public function addDecision(Decision $decision): static
    {
        if (!$this->decisions->contains($decision)) {
            $this->decisions->add($decision);
            $decision->setUser($this);
        }

        return $this;
    }

    public function removeDecision(Decision $decision): static
    {
        if ($this->decisions->removeElement($decision)) {
            // set the owning side to null (unless already changed)
            if ($decision->getUser() === $this) {
                $decision->setUser(null);
            }
        }

        return $this;
    }

    public function getCreatedDecisionsCount(): int
    {
        return $this->decisions->count();
    }

    public function getBiography(): ?string
    {
        return $this->biography;
    }

    public function setBiography(?string $biography): static
    {
        $this->biography = $biography;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): static
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function setAvatarFile(File $image = null): User
    {
        $this->avatarFile = $image;
        if ($image) {
            $this->updatedAt = new DateTime('now');
        }

        return $this;
    }

    public function getAvatarFile(): ?File
    {
        return $this->avatarFile;
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?DateTimeInterface $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Decision>
     */
    public function getExpertUsers(): Collection
    {
        return $this->expertUsers;
    }

    public function addExpertUser(Decision $expertUser): static
    {
        if (!$this->expertUsers->contains($expertUser)) {
            $this->expertUsers->add($expertUser);
            $expertUser->addExpertUser($this);
        }

        return $this;
    }

    public function removeExpertUser(Decision $expertUser): static
    {
        if ($this->expertUsers->removeElement($expertUser)) {
            $expertUser->removeExpertUser($this);
        }

        return $this;
    }

    public function getExpertDecisionsCount(): int
    {
        return $this->expertUsers->count();
    }

    /**
     * @return Collection<int, Decision>
     */
    public function getImpactedUsers(): Collection
    {
        return $this->impactedUsers;
    }

    public function addImpactedUser(Decision $impactedUser): static
    {
        if (!$this->impactedUsers->contains($impactedUser)) {
            $this->impactedUsers->add($impactedUser);
            $impactedUser->addImpactedUser($this);
        }

        return $this;
    }

    public function removeImpactedUser(Decision $impactedUser): static
    {
        if ($this->impactedUsers->removeElement($impactedUser)) {
            $impactedUser->removeImpactedUser($this);
        }

        return $this;
    }

    public function getImpactedDecisionsCount(): int
    {
        return $this->impactedUsers->count();
    }

    /**
     * @return Collection<int, Notification>
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): static
    {
        if (!$this->notifications->contains($notification)) {
            $this->notifications->add($notification);
            $notification->setUser($this);
        }
        return $this;
    }

templates/components/_buttonTop.html.twig
<div id="scroll_to_top">
	<a href="#top"><img src="{{ asset('build/images/arrow.svg')}}" alt="Retourner en haut"/></a>
</div>

templates/components/_decisionCards.html.twig
<div class="background-wave">
	<div class="wave"></div>
</div>

{% if decisions|length > 0 %}
	{{ include('components/_search_form.html.twig') }}
{% endif %}

<div class="decision" id="cardsContainer">
	<div class="container g-0">
		<div class="row">
			{% for decision in decisions %}
				<div class="col-lg-4 col-md-6">
					<div class="card shadow mb-5 border border-0 rounded bg-tertiary">
						<div class="card-body">
							<div class="img-container">
								{% if decision.image %}
									<img class="img" src="{{ asset('uploads/images/decision/' ~ decision.image)}}">
								{% else %}
									<img class="img" src="{{ asset('uploads/images/category/' ~ decision.category.image) }}" alt="Image">
								{% endif %}
							</div>
							<div class="position-relative">

								<div class="card-main">
									{% if decision.user.avatar %}
										<a href="{{ path('app_profile', {'id': decision.user.id}) }}">
											<img class="img-profile rounded-circle position-absolute mx-4" src="{{ asset('uploads/avatar/' ~ decision.user.avatar) }}">
										</a>
									{% else %}
										<a href="{{ path('app_profile', {'id': decision.user.id}) }}">
											<img class="img-profile rounded-circle position-absolute mx-4" src="{{ asset('build/images/profil.png')}}">
										</a>
									{% endif %}
									<div class="color-card">
										<a href="{{ path('app_profile', {'id': decision.user.id}) }}">
											<p class="text-tertiary border-primary fw-bolder fs-5 mx-3 mb-2 border-5 px-2 pb-1 pt-5 border-bottom">{{ decision.user.fullname }}</p>
										</a>
									</div>
								</div>
							</div>
							<div class="statut pt-2 mx-3 text-end">
								<p class="label-status badge rounded-pill p-2">{{ decision.status }}</p>
								<div class="label-category badge rounded-pill p-2">
									{{ decision.category.title }}
								</div>
							</div>
							<h2 class="card-title text-primary fw-bolder p-3 fs-4 mb-0">
								{{ decision.title|u.truncate(50, '...') }}
							</h2>

							<div class="text-end p-3 text-l pt-0 primary mb-1 btn-rounded">
								{% if app.user == decision.user %}
									<a href="{{ path('app_decision_edit', {'id': decision.id}) }}" class="btn btn-card btn-primary mt-3 px-3 rounded-pill text-light bg-primary fw-bold">Modifier</a>
								{% endif %}
								<a href="{{ path('app_decision_show', {'id': decision.id}) }}" class="btn btn-card btn-light mt-3 px-3 rounded-pill text-primary bg-light fw-bold ms-4">En savoir plus</a>

							</div>
							<div class="vote bg-light rounded-pill p-1 px-2">
								<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#507178" class="bi bi-hand-thumbs-up-fill" viewbox="0 0 16 16">
									<path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
								</svg>
								{{ decision.votes|filter(vote => vote.voting == 1)|length }}
								<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#507178" class="bi bi-hand-thumbs-down-fill ms-2" viewbox="0 0 16 16">

									<path d="M6.956 14.534c.065.936.952 1.659 1.908 1.42l.261-.065a1.378 1.378 0 0 0 1.012-.965c.22-.816.533-2.512.062-4.51.136.02.285.037.443.051.713.065 1.669.071 2.516-.211.518-.173.994-.68 1.2-1.272a1.896 1.896 0 0 0-.234-1.734c.058-.118.103-.242.138-.362.077-.27.113-.568.113-.856 0-.29-.036-.586-.113-.857a2.094 2.094 0 0 0-.16-.403c.169-.387.107-.82-.003-1.149a3.162 3.162 0 0 0-.488-.9c.054-.153.076-.313.076-.465a1.86 1.86 0 0 0-.253-.912C13.1.757 12.437.28 11.5.28H8c-.605 0-1.07.08-1.466.217a4.823 4.823 0 0 0-.97.485l-.048.029c-.504.308-.999.61-2.068.723C2.682 1.815 2 2.434 2 3.279v4c0 .851.685 1.433 1.357 1.616.849.232 1.574.787 2.132 1.41.56.626.914 1.28 1.039 1.638.199.575.356 1.54.428 2.591z"/>
								</svg>
								{{ decision.votes|filter(vote => vote.voting == -1)|length }}
							</div>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
</div>

templates/components/_footer.html.twig
<div class="container">
	<footer class="footer row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 border-top border-primary border-4">
		<div class="col mb-3">
			<a href="https://makesense.org/" class="d-flex align-items-center mb-3 link-dark text-decoration-none">
				<img src="{{ asset('build/images/logo-dark.png')}}" class="my-2 mx-4" alt="logo"></a>
		</div>
		<div class="col mb-3"></div>
		<div class="col mb-3">
			<h5 class="fw-bold text-primary">Nous contacter</h5>
			<ul class="nav flex-column">
				<li class="nav-item mb-2">
					<a href="https://makesense.org/contact/#france" class="fw-bold text-primary nav-link p-0 text-muted">Sans frontières</a>
				</li>
			</ul>
		</div>
		<div class="col mb-3">
			<h5 class="fw-bold text-primary">Se rencontrer</h5>
			<ul class="nav flex-column">
				<li class="nav-item mb-2">
					<p class="fw-bold text-primary nav-link p-0 text-muted m-0">36 rue Etienne Dolet</p>
				</li>
				<li class="nav-item mb-2">
					<p class="fw-bold text-primary nav-link p-0 text-muted m-0">75020 Paris</p>
				</li>
				<li class="nav-item mb-2">
					<p class="fw-bold text-primary nav-link p-0 text-muted m-0">France</p>
				</li>
			</ul>
		</div>
		<div class="col mb-3">
			<h5 class="fw-bold text-primary">À l'international</h5>
			<ul class="nav flex-column">
				<li class="nav-item mb-2">
					<a href="https://africa.makesense.org/" class="fw-bold text-primary nav-link p-0 text-muted">Afrique de l'Ouest</a>
				</li>
				<li class="nav-item mb-2">
					<a href="https://americas.makesense.org/" class="fw-bold text-primary nav-link p-0 text-muted">Amériques</a>
				</li>
				<li class="nav-item mb-2">
					<a href="https://france.makesense.org/" class="fw-bold text-primary nav-link p-0 text-muted">France</a>
				</li>
				<li class="nav-item mb-2">
					<a href="https://philippines.makesense.org/" class="fw-bold text-primary nav-link p-0 text-muted">Philippines</a>
				</li>
				<li class="nav-item mb-2">
					<a href="https://lebanon.makesense.org/" class="fw-bold text-primary nav-link p-0 text-muted">Liban</a>
				</li>
			</ul>
		</div>


	</footer>
</div>

templates/components/_navbar.html.twig
<div class="container">

	<nav class="navbar navbar-expand-lg border-bottom border-primary border-4 navbar-transparent bg-transparent">
		<div class="container-fluid mx-3">
			<a class="navbar-brand fs-2 fw-bold text-light mx-0" href="{{ path('home_page') }}"><img src="{{ asset('build/images/logo-dark.png') }}" alt="makesense" width="160px"></a>

			<button class="navbar-toggler border border-primary p-1" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<img src="{{ asset('build/images/menu.svg') }}" alt="menu" width="50px">

			</button>
			<div class="collapse navbar-collapse  justify-content-end fw-semibold" id="navbarNav">
				<ul class="navbar-nav align-items-center gap-3">
					{% if is_granted('ROLE_ADMIN') %}
						<li class="nav-item">
							<a class="link nav-link text-primary fw-bold px-3" href="{{ path('admin_home') }}">Admin</a>
						</li>
					{% endif %}
					<li class="nav-item">
						<a class="link nav-link text-primary fw-bold px-3" href="{{ path('status_home') }}">Les décisions</a>
					</li>
					<li class="nav-item">
						<a class="link nav-link fw-bold text-primary px-3" href="{{ path('app_decision_new') }}">Ajouter une décision</a>
					</li>
					<li class="nav-item">
						<a class="link nav-link text-primary fw-bold px-3" href="{{ path('status_my_decision') }}">Mes décisions</a>

					</li>
					<li class="nav-item">
						<a class="link nav-link text-primary fw-bold px-3" href="{{ path('app_archive') }}">Les archives</a>

					</li>
					<li class="nav-item">
						{{ component('notification') }}
					</li>
					<li class="nav-item text-primary">
						{% if app.user %}

							<a class="profile" href="{{ path('app_profile', {'id': app.user.id}) }}">
								<img class="img-profile rounded-circle border border-2 border-primary" src="{{ app.user.avatar is empty ? asset('build/images/profile.svg') : vich_uploader_asset(app.user) }}" alt="profil">

							</a>

						</li>

						<div class="dropdown profile">
							<button class="link btn-profile p-1 dropdown-toggle text-primary bg-tertiary fw-bold border-tertiary" type="button" data-bs-toggle="dropdown" aria-expanded="false">
								{{ app.user.firstname|first}}
								{{ app.user.lastname|first}}
							</button>
							<ul class="dropdown-menu bg-tertiary border border-tertiary">
								<li>
									<a class="dropdown-item fw-bold" href="{{ path('app_profile', {'id': app.user.id}) }}">Profil</a>

								</li>
								<li class="nav-item text-primary">
									<a class="dropdown-item fw-bold" href="{{ path('app_logout') }}">Déconnexion</a>
								</li>
							</ul>
						</div>
					</li>
				</ul>
			</div>
		{% else %}
			<a class="link nav-link fw-bold text-primary px-3" href="{{ path('app_login') }}">Connexion</a>
		{% endif %}
	</nav>
</div>

templates/components/_navbar_admin.html.twig
<div class="container">
	<nav class="navbar navbar-expand-lg navbar-transparent bg-transparent">
		<div class="container-fluid mx-3">
			<a class="navbar-brand fs-2 fw-bold text-light mx-0" href="{{ path('home_page') }}"><img src="{{ asset('build/images/logo-dark.png') }}" alt="makesense" width="160px"></a>
			<button class="navbar-toggler  border border-primary p-1" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<img src="{{ asset('build/images/menu.svg') }}" alt="menu" width="50px">
			</button>
			<div class="collapse navbar-collapse justify-content-end fw-semibold" id="navbarNav">
				<ul class="navbar-nav align-items-center gap-3">
					<li class="nav-item">
						<a class="link nav-link fw-bold text-primary px-3" href="{{ path('admin_home') }}">Accueil</a>
					</li>
					<li class="nav-item">
						<a class="link nav-link fw-bold text-primary px-3" href="{{ path('admin_decision_index') }}">Décisions</a>
					</li>

					<li class="nav-item">
						<a class="link nav-link fw-bold text-primary px-3" href="{{ path('admin_user_index') }}">Utilisateurs</a>
					</li>
					<li class="nav-item">
						<a class="link nav-link text-primary fw-bold px-3" href="{{ path('admin_category_index') }}">Catégories</a>
					</li>
					<li class="nav-item text-primary">
						{% if app.user %}

							<a class="profile" href="{{ path('app_profile', {'id': app.user.id}) }}">
								<img class="img-profile rounded-circle border border-2 border-primary" src="{{ app.user.avatar is empty ? asset('build/images/profile.svg') : vich_uploader_asset(app.user) }}" alt=" profil">

							</a>

						</li>

						<div class="dropdown profile">
							<button class="link btn-profile p-1 dropdown-toggle text-primary bg-tertiary fw-bold border-tertiary" type="button" data-bs-toggle="dropdown" aria-expanded="false">
								{{ app.user.firstname|first }}
								{{ app.user.lastname|first }}
							</button>
							<ul class="dropdown-menu bg-tertiary border border-tertiary">
								<li>
									<a class="dropdown-item fw-bold" href="{{ path('app_profile', {'id': app.user.id}) }}">Profil</a>

								</li>
								<li class="nav-item text-primary">
									<a class="dropdown-item fw-bold" href="{{ path('app_logout') }}">Déconnexion</a>
								</li>
							</ul>
						</div>

					{% else %}
						<a class="link nav-link fw-bold text-primary px-3" href="{{ path('app_login') }}">Connexion</a>
					{% endif %}
				</li>

			</ul>
		</div>
	</nav>
</div>

templates/components/_search_form.html.twig
<div class="nav-decision">
	<nav class="navbar navbar-expand-lg bg-tertiary shadow border border-3 border-primary mb-5 container">
		<div class="container nav-item d-flex justify-content-center bg-none">

			<p class="my-auto text-primary mx-3 d-none d-lg-block fw-bold">Filtres</p>
			<span class="vertical-line d-none mx-5 d-md-block"></span>

			{{ form_start(form, {'attr': {'class': 'form-class bg-none'}}) }}

			<div class="row">

				<div class="col-lg-4 col-md-12 my-3">

					{{ form_widget(form.status, {'attr': {'onchange':'this.form.submit()', 'class': 'form-class text text-primary fw-bold border border-light rounded-pill form-control bg-tertiary'}}) }}
				</div>
				<div class="col-lg-4 col-md-12 my-3">

					{{ form_widget(form.category, {'attr': {'onchange':'this.form.submit()', 'class': 'form-class text text-primary fw-bold border border-light rounded-pill form-control bg-tertiary'}}) }}

				</div>

				<div class="search-bar col-lg-4 col-md-12 my-3 d-flex justify-content-between">

					{{ form_widget(form.search, {'attr': {'class': 'form-class form-control rounded-pill fw-bold border-light bg-tertiary', 'placeholder': 'Rechercher par Titre'}}) }}


					<button class="btn border-none me-4" type="submit"><img src="{{ asset('build/images/search.svg')}}" style="width:25px" alt="Rechercher"></button>

				</div>
				{{ form_end(form) }}
			</div>
		</nav>
	</div>

templates/components/_workflowStatus.html.twig
{% if workflowName is not null and workflow_can(decision, workflowName) %}
	<form method="post" action="{{ path('app_change', {'id': decision.id, 'toStatus': workflowName}) }}" >
		<input type="hidden" name="_token" value="{{ csrf_token('workflow_change' ~ decision.id) }}">
		<div class="text-end">

			<button class="btn btn-light text-primary my-2 border border-secondary bg-white fw-bold rounded-pill mt-5">
				{% if constant('App\\Entity\\Decision::WORKFLOWS')[workflowName] is defined %}
					{{ constant('App\\Entity\\Decision::WORKFLOWS')[workflowName] }}
				{% endif %}
			</button>

		</div>
	</form>
{% endif %}

templates/components/activationSwitch.html.twig
<div{{attributes}}>
	<div class="form-check form-switch">
		<input class="form-check-input" type="checkbox" role="switch" id="user{{ user.id }}" {{ user.isActivated ? 'checked'}} data-action="live#action" data-action-name="toggleActivation">
		<label class="form-check-label" for="user{{ user.id }}"></label>
	</div>
</div>

templates/components/role.html.twig
<div{{attributes}}>
	<div class="btn-group">
		<button type="button" class="role btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown">
			{% set roleLabels = {
        		'ROLE_ADMIN': 'Administrateur',
       			'ROLE_EMPLOYEE': 'Salarié',
        		'ROLE_USER': 'Bénévole'
    		} %}
			{{ roleLabels[user.roles.0] }}
		</button>

		<ul class="dropdown-menu">
			<li>
				<a class="dropdown-item" href="#" data-action="live#action" data-action-name="updateRole(newRole=ROLE_ADMIN)">Administrateur</a>
			</li>
			<li>
				<a class="dropdown-item" href="#" data-action="live#action" data-action-name="updateRole(newRole=ROLE_EMPLOYEE)">Salarié</a>
			</li>
			<li>
				<a class="dropdown-item" href="#" data-action="live#action" data-action-name="updateRole(newRole=ROLE_USER)">Bénévole</a>
			</li>
		</ul>
	</div>
</div>